name: Release Binary (Linux)

on:
    push:
        tags:
            - "v*"

jobs:
    build-release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up Rust
              uses: dtolnay/rust-toolchain@stable

            - name: Build binary
              run: cargo build --release

            - name: Upload binary to GitHub Release
              uses: softprops/action-gh-release@v1
              with:
                  files: target/release/self-reposcope
                  token: ${{ secrets.REPOSCOPE_TOKEN }}
